# Generated by Django 4.1 on 2022-09-24 23:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='edges1week',
            fields=[
                ('interval', models.DateTimeField(primary_key=True, serialize=False)),
                ('Pickup_Community_Area', models.TextField()),
                ('Dropoff_Community_Area', models.TextField()),
                ('tripcount', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('faresum', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('fareavg', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('farestddevp', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('faremedian', models.DecimalField(blank=True, decimal_places=2, max_digits=13, null=True)),
                ('timeavg', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('timestddevp', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('timemedian', models.DecimalField(blank=True, decimal_places=0, max_digits=11, null=True)),
                ('mileavg', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('milestddevp', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('milemedian', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
                ('avgdirdeg', models.DecimalField(blank=True, decimal_places=1, max_digits=12, null=True)),
            ],
            options={
                'db_table': 'taxi_edges_1week',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Ocaf',
            fields=[
                ('year', models.DecimalField(decimal_places=0, max_digits=4, primary_key=True, serialize=False)),
                ('state', models.TextField()),
                ('ocaf', models.DecimalField(blank=True, decimal_places=1, max_digits=2, null=True)),
                ('sewer', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('wages', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('benefits', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('goods', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('insurance', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('proptax', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('elec', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('gas', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
                ('oil', models.DecimalField(blank=True, decimal_places=3, max_digits=4, null=True)),
            ],
            options={
                'db_table': 'ocaf',
                'managed': False,
            },
        ),
    ]
